{% set name = "source" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fair-ease/Source/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b92fd32f80d6f894da9f130b792fddb3a6f0e1b56aca4d01baa653ed7bcbc1ff
  paths:
    - SOURCE/obs_postpro/probes_names.csv
    - SOURCE/obs_postpro/url_countries.csv

build:
  number: 1
  script: 
    - {{ PYTHON }} -m pip install . -vv
    - cp SOURCE/obs_postpro/probes_names.csv $PREFIX/lib/python$PY/site-packages/SOURCE/obs_postpro/
    - cp SOURCE/obs_postpro/url_countries.csv $PREFIX/lib/python$PY/site-packages/SOURCE/obs_postpro/

requirements:
  host:
    - python
    - pip
    - poetry-core

  run:
    - python
    - pykml
    - lxml
    - numpy
    - pandas
    - netcdf4
    - seawater
    - scipy
    - scikit-learn
    - unidecode
    
test:
  imports:
    - SOURCE


about:
  home: https://github.com/fair-ease/Source
  license:  CC-BY-NC-SA-4.0
  license_file: LICENSE.txt
  summary: The package Sea Observations Utility for Reprocessing, Calibration and Evaluation (SOURCE) aims to manage jobs with in situ observations and model data from Ocean General Circulation Models (OGCMs)

extra:
  recipe-maintainers:
    - marie59
